# **Exploratory Data Analysis**

In [3]:
import numpy as np
import pandas as pd

### **1. Load the Dataset**

In [4]:

df = pd.read_csv(r'C:\Users\zakir hussain\OneDrive\Desktop\Laptop-Price-Predictor-main\notebooks\latopData.csv')

**Display top 5 rows to get to know about dataset:**

In [5]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

### **2. Data Summary**

**Display basic information about the dataset**

In [6]:
df.shape

(1303, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Cpu               1303 non-null   object
 6   Ram               1303 non-null   object
 7   Memory            1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price             1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

**Check for missing values**

In [8]:
df.isnull().sum()

Unnamed: 0          0
Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

**Check for duplicate values**

In [9]:
df.duplicated().sum()

np.int64(0)

**Initial Insights:**

**Dataset Overview:**   
- The dataset consists of 1303 records and 11 attributes.

**Unused Column:**  
- The column Unnamed: 0 does not provide any meaningful information and can be dropped from the dataset.

**Data Structuring Opportunity:**   
- **Feature Engineering:** Several attributes (ScreenResolution, Cpu, Ram, Memory, Gpu) contain multiple types of information within single columns. These attributes can be parsed and split into separate columns to improve data organization and model interpretability.

**Data Type Adjustments:**  
- **Column Types:** The columns Ram and Weight are currently stored as objects (likely due to suffixes or formatting). Converting these columns to appropriate data types (e.g., integer for Ram, float for Weight) will facilitate numerical operations and analysis.    
- **Price Column:** Price column can be formatted as integers.

**Data Integrity:**
- **Missing Values:** There are no missing or null values observed in the dataset, ensuring data completeness and reliability for initial analysis.

## **3. Data Pre Processing**

**Remove Unsed Column**

In [10]:
df.drop(columns= 'Unnamed: 0', inplace= True)

In [11]:
df.columns

Index(['Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu', 'Ram',
       'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='object')

**Setting the type of Ram and Weight column**

In [12]:
# removing the suffixes of columns:
df['Ram'] = df['Ram'].str.replace('GB','')
df['Weight'] = df['Weight'].str.replace('kg','')

In [13]:
# assigning the dtype of columns:
df['Price'] = df['Price'].astype('int64')
df['Ram'] = df['Ram'].astype('int64')
df['Weight'] = df['Weight'].astype('float64')

In [14]:
# ensuring the changes:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1303 non-null   object
 1   TypeName          1303 non-null   object
 2   Inches            1303 non-null   float64
 3   ScreenResolution  1303 non-null   object
 4   Cpu               1303 non-null   object
 5   Ram               1303 non-null   int64
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   float64
 10  Price             1303 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 112.1+ KB

In [15]:
pre_processed_df = df
pre_processed_df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095

In [ ]:
pre_processed_df.to_csv('', index= False)

OSError: Cannot save file into a non-existent directory: 'D:\PROJECTS\ML Projects\Laptop Price Predictor\data\pre processed'